# Generated by Django 4.2.5 on 2024-01-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_otp_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000014AA32A05E0>', max_length=200),
        ),
    ]
