# Generated by Django 5.0 on 2024-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='vishnusreqourse@gmail.com', max_length=254, unique=True),
        ),
    ]
