# Generated by Django 5.0 on 2024-04-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_payment_refunded_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
