# Generated by Django 5.0 on 2024-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_orderplaced_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
